version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: airflow_tutorial
      POSTGRES_USER: airflow_tutorial
      POSTGRES_DB: airflow_tutorial

